driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: server
    run_list:
      - recipe[npm_lazy::server]
    attributes:

  - name: client
    run_list:
      - recipe[npm_lazy::client]
    attributes:
      npm_lazy:
        client:
          install_nodejs: true
