---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: server-debian-8
          suite: server-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-debian-9
          suite: server-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-centos-6
          suite: server-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-centos-7
          suite: server-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-fedora-26
          suite: server-fedora-26
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-fedora-27
          suite: server-fedora-27
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-ubuntu-1404
          suite: server-ubuntu-1404
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-ubuntu-1604
          suite: server-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-opensuse-leap
          suite: server-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-debian-8
          suite: client-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-debian-9
          suite: client-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-centos-6
          suite: client-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-centos-7
          suite: client-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-fedora-26
          suite: client-fedora-26
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-fedora-27
          suite: client-fedora-27
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-ubuntu-1404
          suite: client-ubuntu-1404
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-ubuntu-1604
          suite: client-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-opensuse-leap
          suite: client-opensuse-leap
          requires: *lint_and_unit
      - final:
          requires:
            - server-debian-8
            - server-debian-9
            - server-centos-6
            - server-centos-7
            - server-fedora-26
            - server-fedora-27
            - server-ubuntu-1404
            - server-ubuntu-1604
            - server-opensuse-leap
            - client-debian-8
            - client-debian-9
            - client-centos-6
            - client-centos-7
            - client-fedora-26
            - client-fedora-27
            - client-ubuntu-1404
            - client-ubuntu-1604
            - client-opensuse-leap
